### ISSUE TITLE
Move Pass date / timerequested to a single datetime.

### ISSUE THREAD

**Issue by armaangoel78** [CHSCodeForChange/PassMaster-Web#16]
This may make more sense for the website, but dart doesn't even contain a date type or a time type (only a datetime type). Therefore it will be easier just to move back to the way it used to be, but we can simply make it a date time. We can still achieve the same functionality we'll just have to have the date field combine with the time field when the model is created.

**Comment by jpaav** [comment]
@armaangoel78 That's not the best design though. Are you sure we can't store it the way we do now (One date, 2-6 times) and combine it when we send the data to dart? Otherwise, we will be storing potentially 6x the dates.

**Comment by armaangoel78** [comment]
@jpaav it shouldn't matter the date and time will all be the same object. In fact, technically it will store one less object. Plus it will make alot more things easier as you won't have to keep referencing the date.
