### ISSUE TITLE
Require the teacher to be somewhere on the pass for them to create it

### ISSUE THREAD

**Issue by jpaav** [CHSCodeForChange/PassMaster-Web#24]
Right now a teacher can create a pass between two totally different teachers for a student without their name being on the pass whatsoever. They should need to be either the origin or destination teacher

**Comment by armaangoel78** [comment]
@jpaav I think its best to keep the system dynamic. Also, consider the library pass where, say, the english teacher must write a pass for a student to leave his/her homeroom teacher to go the library.

**Comment by jpaav** [comment]
Ok but we should store who made the pass on this case

**Comment by armaangoel78** [comment]
Yeah I'm with you there

**Comment by armaangoel78** [comment]
#32 has replaced this
