### ISSUE TITLE
Styling of autocomplete invisible in IE

### ISSUE THREAD

**Issue by armaangoel78** [CHSCodeForChange/PassMaster-Web#27]
This was discovered in the Wiseman meeting. Apparently the login page autocomplete doesn't show up when in IE.

**Comment by jpaav** [comment]
I think this is because of CSS styling which makes the text effectively invisible

**Comment by jpaav** [comment]
Fixed, IE does not allow transparent background colors. Added a line that makes the background nontransparent since we didn't need it to be in the first place
