### ISSUE TITLE
Store the pass creator

### ISSUE THREAD

**Issue by armaangoel78** [CHSCodeForChange/PassMaster-Web#32]
Currently teachers can make passes between two teachers that doesn't include themselves. This is fine, but we should definitely store who created the pass as well.

**Comment by armaangoel78** [comment]
#24 is what this replaces

**Comment by computerquest** [comment]
This is closed because issue #24 is closed.

**Comment by jpaav** [comment]
>This is closed because issue #24 is closed.

@computerquest issue #24 is closed because this replaced it. This issue should be open
