### ISSUE TITLE
No redirect to login from unauthorized pages

### ISSUE THREAD

**Issue by evankenyon** [CHSCodeForChange/PassMaster-Web#45]
<img width="1280" alt="screenshot 2018-11-29 09 11 17" src="https://user-images.githubusercontent.com/23245802/49227281-bc16ac00-f3b6-11e8-8274-89a26f9d2be5.png">

When a user is unauthorized to view a page for any given reason, they are not redirected to the login page and instead see an error screen.

**Comment by jpaav** [comment]
This is only because we have debug set to true for local and production servers. Our 404 and 500 pages, however, are not properly made so making those should be a priority. See issue #46 for more info.
